# my global config
global:
  scrape_interval: 15s # 设置抓取(pull)时间间隔，默认是1m
  evaluation_interval: 15s # 设置rules评估时间间隔，默认是1m
  # scrape_timeout is set to the global default (10s).

# 告警管理配置，默认配置
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'    # 配置连通 alertmanager





# 加载rules，并根据设置的时间间隔定期评估
rule_files:
  - "./rules/node_down.yml"


scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: 'node-localhost'
  static_configs:
  - targets: ['192.168.0.107:9100']
